///
/// @Generated by Mockolo
///



import Foundation
import LinkPresentation
import RxRelay
import RxSwift
import SwiftSoup
@testable import Domain


public final class AppleLoginUseCaseMock: AppleLoginUseCase {
    public init() { }


    public private(set) var executeCallCount = 0
    public var executeArgValues = [String]()
    public var executeHandler: ((String) -> (Single<Bool>))?
    public func execute(identity: String) -> Single<Bool> {
        executeCallCount += 1
        executeArgValues.append(identity)
        if let executeHandler = executeHandler {
            return executeHandler(identity)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

public final class GoogleLoginUseCaseMock: GoogleLoginUseCase {
    public init() { }


    public private(set) var executeCallCount = 0
    public var executeArgValues = [String]()
    public var executeHandler: ((String) -> (Single<Bool>))?
    public func execute(access: String) -> Single<Bool> {
        executeCallCount += 1
        executeArgValues.append(access)
        if let executeHandler = executeHandler {
            return executeHandler(access)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

public final class LoginRepositoryMock: LoginRepository {
    public init() { }


    public private(set) var requestGoogleLoginCallCount = 0
    public var requestGoogleLoginArgValues = [String]()
    public var requestGoogleLoginHandler: ((String) -> (Single<Bool>))?
    public func requestGoogleLogin(accessToken: String) -> Single<Bool> {
        requestGoogleLoginCallCount += 1
        requestGoogleLoginArgValues.append(accessToken)
        if let requestGoogleLoginHandler = requestGoogleLoginHandler {
            return requestGoogleLoginHandler(accessToken)
        }
        fatalError("requestGoogleLoginHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var requestAppleLoginCallCount = 0
    public var requestAppleLoginArgValues = [String]()
    public var requestAppleLoginHandler: ((String) -> (Single<Bool>))?
    public func requestAppleLogin(identity: String) -> Single<Bool> {
        requestAppleLoginCallCount += 1
        requestAppleLoginArgValues.append(identity)
        if let requestAppleLoginHandler = requestAppleLoginHandler {
            return requestAppleLoginHandler(identity)
        }
        fatalError("requestAppleLoginHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var logoutCallCount = 0
    public var logoutHandler: (() -> (Single<Bool>))?
    public func logout() -> Single<Bool> {
        logoutCallCount += 1
        if let logoutHandler = logoutHandler {
            return logoutHandler()
        }
        fatalError("logoutHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var requestSignUpCallCount = 0
    public var requestSignUpArgValues = [(String, Int?, String?, String?, String)]()
    public var requestSignUpHandler: ((String, Int?, String?, String?, String) -> (Single<Bool>))?
    public func requestSignUp(idToken: String, age: Int?, gender: String?, nickname: String?, social: String) -> Single<Bool> {
        requestSignUpCallCount += 1
        requestSignUpArgValues.append((idToken, age, gender, nickname, social))
        if let requestSignUpHandler = requestSignUpHandler {
            return requestSignUpHandler(idToken, age, gender, nickname, social)
        }
        fatalError("requestSignUpHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var getMeCallCount = 0
    public var getMeHandler: (() -> (Single<Void>))?
    public func getMe() -> Single<Void> {
        getMeCallCount += 1
        if let getMeHandler = getMeHandler {
            return getMeHandler()
        }
        fatalError("getMeHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var deleteAccountCallCount = 0
    public var deleteAccountHandler: (() -> (Single<Void>))?
    public func deleteAccount() -> Single<Void> {
        deleteAccountCallCount += 1
        if let deleteAccountHandler = deleteAccountHandler {
            return deleteAccountHandler()
        }
        fatalError("deleteAccountHandler returns can't have a default value thus its handler must be set")
    }
}

public final class LogoutUseCaseMock: LogoutUseCase {
    public init() { }


    public private(set) var executeCallCount = 0
    public var executeHandler: (() -> (Single<Bool>))?
    public func execute() -> Single<Bool> {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return executeHandler()
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

public final class SignUpUseCaseMock: SignUpUseCase {
    public init() { }


    public private(set) var executeCallCount = 0
    public var executeArgValues = [(String, Int?, String?, String?, String)]()
    public var executeHandler: ((String, Int?, String?, String?, String) -> (Single<Bool>))?
    public func execute(idToken: String, age: Int?, gender: String?, nickname: String?, social: String) -> Single<Bool> {
        executeCallCount += 1
        executeArgValues.append((idToken, age, gender, nickname, social))
        if let executeHandler = executeHandler {
            return executeHandler(idToken, age, gender, nickname, social)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

