///
/// @Generated by Mockolo
///



import Foundation
import RxSwift
@testable import Domain


public final class LoginRepositoryMock: LoginRepository {
    public init() { }


    public private(set) var requestGoogleLoginCallCount = 0
    public var requestGoogleLoginArgValues = [String]()
    public var requestGoogleLoginHandler: ((String) -> (Single<String>))?
    public func requestGoogleLogin(accessToken: String) -> Single<String> {
        requestGoogleLoginCallCount += 1
        requestGoogleLoginArgValues.append(accessToken)
        if let requestGoogleLoginHandler = requestGoogleLoginHandler {
            return requestGoogleLoginHandler(accessToken)
        }
        fatalError("requestGoogleLoginHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var requestAppleLoginCallCount = 0
    public var requestAppleLoginArgValues = [(String, String)]()
    public var requestAppleLoginHandler: ((String, String) -> (Single<String>))?
    public func requestAppleLogin(identity: String, authorization: String) -> Single<String> {
        requestAppleLoginCallCount += 1
        requestAppleLoginArgValues.append((identity, authorization))
        if let requestAppleLoginHandler = requestAppleLoginHandler {
            return requestAppleLoginHandler(identity, authorization)
        }
        fatalError("requestAppleLoginHandler returns can't have a default value thus its handler must be set")
    }
}

public final class AppleLoginUseCaseMock: AppleLoginUseCase {
    public init() { }


    public private(set) var excuteCallCount = 0
    public var excuteArgValues = [(String, String)]()
    public var excuteHandler: ((String, String) -> (Single<String>))?
    public func excute(identity: String, authorization: String) -> Single<String> {
        excuteCallCount += 1
        excuteArgValues.append((identity, authorization))
        if let excuteHandler = excuteHandler {
            return excuteHandler(identity, authorization)
        }
        fatalError("excuteHandler returns can't have a default value thus its handler must be set")
    }
}

public final class GoogleLoginUseCaseMock: GoogleLoginUseCase {
    public init() { }


    public private(set) var excuteCallCount = 0
    public var excuteArgValues = [String]()
    public var excuteHandler: ((String) -> (Single<String>))?
    public func excute(access: String) -> Single<String> {
        excuteCallCount += 1
        excuteArgValues.append(access)
        if let excuteHandler = excuteHandler {
            return excuteHandler(access)
        }
        fatalError("excuteHandler returns can't have a default value thus its handler must be set")
    }
}

