///
/// @Generated by Mockolo
///

import Domain
import Foundation
@testable import PresentationInterface
import UIKit

public final class LoginBuildableMock: LoginBuildable {
  public init() {}

  public private(set) var buildCallCount = 0
  public var buildArgValues = [LoginPayload]()
  public var buildHandler: ((LoginPayload) -> (UIViewController))?
  public func build(payload: LoginPayload) -> UIViewController {
    buildCallCount += 1
    buildArgValues.append(payload)
    if let buildHandler {
      return buildHandler(payload)
    }
    return UIViewController()
  }
}
