///
/// @Generated by Mockolo
///



import Foundation
@testable import PBAuthInterface


public final class PBAuthLocalDataSourceMock: PBAuthLocalDataSource {
    public init() { }
    public init(accessToken: String? = nil, refreshToken: String? = nil, social: String? = nil, email: String? = nil) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.social = social
        self.email = email
    }


    public private(set) var accessTokenSetCallCount = 0
    public var accessToken: String? = nil { didSet { accessTokenSetCallCount += 1 } }

    public private(set) var refreshTokenSetCallCount = 0
    public var refreshToken: String? = nil { didSet { refreshTokenSetCallCount += 1 } }

    public private(set) var socialSetCallCount = 0
    public var social: String? = nil { didSet { socialSetCallCount += 1 } }

    public private(set) var emailSetCallCount = 0
    public var email: String? = nil { didSet { emailSetCallCount += 1 } }
}

