# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "AppVersion 올리기"
  lane :bump do |options|

  if options[:version]

    major, minor, patch = options[:version].split(".")

    # major, minor, patch 값을 숫자로 변환
    major = major.to_i
    minor = minor.to_i
    patch = patch.to_i

    increment_version_number(
      version_number: "#{major}.#{minor}.#{patch}",
      xcodeproj: "./Projects/App/Joosum.xcodeproj"
    )

    increment_build_number(
      build_number: 0,
      xcodeproj: "./Projects/App/Joosum.xcodeproj"
    )
  else

    increment_build_number(
      build_number: latest_testflight_build_number(username: ENV['APPLE_ID'], app_identifier: ENV['APP_IDENTIFIER'] ) + 1,
      xcodeproj: "./Projects/App/Joosum.xcodeproj"
    )
  end

  end
end
