# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :upload do
    match

    increment_build_number(
        build_number: latest_testflight_build_number(
		username: ENV['APPLE_ID'],
		app_identifier: ENV['APP_IDENTIFIER']
		) + 1,
        xcodeproj: "./Projects/Joosum/Joosum.xcodeproj"
    )

    build_app(workspace: "joosum.xcworkspace", scheme: "Joosum")

    upload_to_testflight(
	username: ENV['APPLE_ID'],
	app_identifier: ENV['APP_IDENTIFIER'],
        skip_submission: true,
	skip_waiting_for_build_processing: true
    )
    
  end
end
