///
/// @Generated by Mockolo
///



import FirebaseAnalytics
import Foundation
@testable import PBAnalyticsInterface


public final class PBAnalyticsMock: PBAnalytics {
    public init() { }


    public private(set) var logCallCount = 0
    public var logArgValues = [PBAnalyticsType]()
    public var logHandler: ((PBAnalyticsType) -> ())?
    public func log(type: PBAnalyticsType)  {
        logCallCount += 1
        logArgValues.append(type)
        if let logHandler = logHandler {
            logHandler(type)
        }
        
    }
}

